### ISSUE TITLE
Unable to use the command

### ISSUE THREAD

**Issue by guillaumepotier** [flopp/StravaExportToGPX#7]
Hi there,

I'm trying to make your command work on my fresh Strava export, and I'm having this error when I just try to list the activity types of my export:

```bash
[ 19:07 username pc27 ~/Developement/StravaExportToGPX ] ./strava2gpx.py --input ~/Downloads/export_4312866.zip --list-types
Activity types found in /Users/username/Downloads/export_4312866.zip:
Traceback (most recent call last):
  File "./strava2gpx.py", line 243, in <module>
    main()
  File "./strava2gpx.py", line 190, in main
    for activity in get_activities(zip_file, activities_csv)
  File "./strava2gpx.py", line 190, in <listcomp>
    for activity in get_activities(zip_file, activities_csv)
KeyError: 'type'
```

I'm using `python` `3.7.2` and `gpsbabel` `1.5.4`

Thanks for your help!

Best

**Comment by flopp** [comment]
Thanks for the report!

Could you manually unzip `export_4312866.zip` and attach the first few lines of `activities.csv` to this issue? Especially the first line is crucial, since it contains the CSV's column names. You may want to anonymize the data before posting it here.

**Comment by flopp** [comment]
Oh, I think I found the issue! Strava seems have started translating the field names to your local language. In my recent Strava export (which I've just downloaded), the field names are in German -> so the script doesn't work for me, either!

**Comment by guillaumepotier** [comment]
Hi there,
Thanks for having a look. I'll try to test your latest commit soon. Best
